### ISSUE TITLE
Modifier en page d’accueil les textes pour les lecteurs et bibliothécaires

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#18]
(si possible à supprimer)

**Comment by aurelberra** [comment]
Est-il finalement possible de supprimer les rubriques ?

Sinon, peut-être vaut-il mieux simplement y mettre un lien vers le site de la revue en rappelant qu'elle est publiée en libre accès ? Si tu me confirmes que cela te semble convenir, je peux faire la modification sur le site OJS, @emchateau.

**Comment by aurelberra** [comment]
Je m'aperçois que j'avais déjà fait ces modifications, il y a assez longtemps, mais que le site les avait effacées ou jamais affichées. Je viens de faire une seconde tentative – les textes en HTML sont sauvegardés dans notre dossier partagé, sous `ojs` (fichier préfixé par la date du jour).

**Comment by emchateau** [comment]
ok merci. Il me semble qu’à l’époque, c’était en raison du pb de cache que nous avions rencontré.
