### ISSUE TITLE
Message aux auteurs vide

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#32]
> De: Sébastien Poublanc <sebastien.poublanc@gmail.com>
> Objet: [HN] Décision de l’éditrice ou éditeur
> Date: 2 mars 2020 à 12:34:13 UTC+1
> À: Flo Jestin <fjm.daniel@wanadoo.fr>
>
>
>
> ________________________________________________________________________
> Humanités numériques

**Comment by emchateau** [comment]
Je suppose une fausse manipulation au moment de la préparation du message.

**Comment by florencedaniel29** [comment]
@emchateau 
fermer cette tâche, je pense
