### ISSUE TITLE
Message Nouvel avis de Humanités numériques à modifier : titre « {$title} »

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#34]
Modifier le message suivant qui arrive aux éditeurs quand un nouvel article est soumis pour qu'il n'y ait pas « {$title} »

Vous avez un nouvel avis de Humanités numériques :

Un nouvel article ayant pour titre « {$title} » a été soumis. Une éditrice ou un éditeur doit lui être assigné(e).

Lien : http://revue-humanites-numeriques.humanisti.ca/index.php/hn/workflow/submission/12

Revue Humanités numériques

________________________________________________________________________
Humanités numériques

**Comment by emchateau** [comment]
Pas dans ojs/locale voir dans pkp-lib

**Comment by emchateau** [comment]
Introuvable...

**Comment by emchateau** [comment]
EDITOR_ASSIGN, déjà corrigé
