### ISSUE TITLE
Modifier le message d'attribution aux éditeurs invités

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#36]
en gras les modifications à apporter (je les ai faites à la main pour assigner le premier article du dossier SIG aux 5 éditeurs invités

Chère/cher **Rédacteur -> Editeur invité**,

La proposition intitulée « Les défis d’une approche multi-sources des dynamiques diachroniques d’occupation du sol » pour la revue Humanités numériques vous a été attribuée. Il vous appartient donc, en tant **que rédactrice ou rédacteur de rubrique-> qu'éditeur invité ou éditrice invitée**, de faire suivre à cet article le processus d’évaluation.

Lien de la proposition : URL
Nom d’utilisatrice ou d’utilisateur : Nom d’utilisateur

Avec tous nos remerciements,

Florence Daniel
florence.daniel@mshb.fr

**Comment by emchateau** [comment]
Nous pouvons le changer spécifiquement dans notre instance. Toutefois, c’est le même message qui est utilisé pour les rédacteurs. Je pense que nous devrions le faire manuellement lors de l’envoi à des rédacteurs invités, ou bien  utiliser un autre modèle de courriel prédéfini.

**Comment by florencedaniel29** [comment]
on en parle demain.

**Comment by emchateau** [comment]
Fait mais on ne comprends pas comment définir les colonnes expéditeur destinataire
