### ISSUE TITLE
flux révision

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#43]
Merci d’avoir accepté d’évaluer ce texte pour la revue XXX. Votre rôle consiste à assister le Comité éditorial dans la préparation de la revue en déterminant la qualité de la proposition. Votre expertise contribuera avec celle d’un autre évaluateur à déterminer si l’article doit être publié. Les évaluateurs fournissent également des éléments de réflexion constructifs aux auteurs pour améliorer la qualité et la rigueur intellectuelle du contenu de l’article.
-->
Merci d’avoir accepté d’évaluer ce texte pour la revue XXX. Votre rôle consiste à assister **l’équipe éditoriale** dans la préparation de la revue en déterminant la qualité de la proposition. Votre expertise contribuera avec celle d’un autre évaluateur à déterminer si l’article doit être publié. Les évaluateurs fournissent également des éléments de réflexion constructifs aux auteurs pour améliorer la qualité et la rigueur intellectuelle du contenu de l’article.

**Comment by florencedaniel29** [comment]
@emchateau 
fermer cette tâche ?
