### ISSUE TITLE
Aedificare recommandations

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#44]
Remplacer les avis par défaut par :
Avis de l’expert concernant la publication de l’étude dans Ædificare
- Accepter sans aucune modification
- Accepter avec des modifications mineures
- À réévaluer après de profondes modifications
- Rejeter, n’entre pas dans le champ de la revue
- Rejeter, n’atteint pas le niveau scientifique requis

**Comment by emchateau** [comment]
<img width="634" alt="Capture d’écran 2020-05-11 à 09 32 41" src="https://user-images.githubusercontent.com/818621/81567516-68a9db00-936a-11ea-853e-9e334d020137.png">

**Comment by florencedaniel29** [comment]
fermer car redondantes avec 50 ? @emchateau
