### ISSUE TITLE
Message nouveau cycle évaluation

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#45]
Nous vous invitons à proposer une version révisée de votre texte, en tenant compte des remarques formulées.

--> Nous vous invitons à proposer une version révisée de votre texte, en tenant compte des remarques formulées. Cette nouvelle proposition fera l’objet d’un nouvel examen en vue de sa publication.

**Comment by florencedaniel29** [comment]
@emchateau 
fermer cette tâche ?
