### ISSUE TITLE
Liste de vérifications de la soumisssion

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#46]
Liste de vérifications de la soumisssion --> Liste de vérification de la soumission

Vous devez lire et reconnaître que vous avez rempli les conditions ci-dessous avant de poursuivre. --> adoucir

**Comment by florencedaniel29** [comment]
PROPOSITION : 
Remplacer : 
"**Liste de vérifications de la soumission**
Vous devez lire et reconnaître que vous avez rempli les conditions ci-dessous avant de poursuivre".

PAR : 
"**Points de contrôle avant soumission**
Veuillez confirmer que votre texte remplit bien les conditions ci-dessous avant de poursuivre la procédure."

**Comment by emchateau** [comment]
done à publier
