### ISSUE TITLE
Changer intitulés

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#50]
- Accepter la proposition
- Révisions requises> Accepter sous réserve de révisions mineures
- Soumettre de nouveau pour évaluation > Soumettre de nouveau avec évaluation
- Soumettre à nouveau ailleurs > Suggérer l’envoi à une autre revue
- Refuser la proposition
- Voir les commentaires

**Comment by florencedaniel29** [comment]
![Capture d’écran 2020-09-10 à 10 48 03](https://user-images.githubusercontent.com/57366511/93336974-c7a3c300-f828-11ea-923e-a0f75b354a50.png)

J'ai repris les formulations dans les messages types :

- Accepter la proposition
- Révisions requises > Accepter sous réserve de révisions [sans ajouter mineures]
- Soumettre de nouveau pour évaluation > Accepter sous condition de révisions importantes et d’une seconde évaluation
- Soumettre à nouveau ailleurs > Suggérer une autre revue
- Refuser la proposition
- Voir les commentaires

**Comment by aurelberra** [comment]
La liste de @florencedaniel29 est parfaite.

Je m'interroge sur l'option "Voir les commentaires", que nous n'avons jamais discutée. Est-elle utile ?

**Comment by emchateau** [comment]
Fait cf. #50
retirer mineures
