### ISSUE TITLE
Mention du statut "demande de révision avec resoumission" entre ##

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#53]
![Capture d’écran 2020-09-10 à 17 00 20](https://user-images.githubusercontent.com/57366511/93336903-a80c9a80-f828-11ea-9f36-4bc32b95f109.png)

**Comment by emchateau** [comment]
##editor.submission.roundStatus.submissionResubmitted##

**Comment by emchateau** [comment]
##editor.submission.roundStatus.resubmitForReview
