### ISSUE TITLE
Coquilles à corriger

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#54]
![Capture d’écran 2020-09-10 à 10 45 58](https://user-images.githubusercontent.com/57366511/93337487-7ba54e00-f829-11ea-8417-ea39a9247607.png)

Évaluation envoyé > Évaluation envoyée

![Capture d’écran 2020-09-10 à 16 06 31](https://user-images.githubusercontent.com/57366511/93337558-97a8ef80-f829-11ea-980b-b54fa87a7362.png)

Une nouvelle entrée vient d'être ajouté > Une nouvelle entrée vient d'être ajoutée

**Comment by emchateau** [comment]
done à publier
