### ISSUE TITLE
Précision sur l’anonymat

### ISSUE THREAD

**Issue by emchateau** [emchateau/ojs#60]
Ajouter une précision sur l’anonymat ? 
"De plus, vous pouvez transférer des fichiers que le rédacteur et/ou l’auteur pourront consulter, y compris les versions révisées des fichiers d’examen originaux."

**Comment by florencedaniel29** [comment]
"Nous vous remercions vivement d’avoir accepté de réaliser une évaluation pour la revue Humanités numériques. Votre avis nous permettra de prendre une décision de publication, tout en aidant les auteurs et autrices à améliorer leur texte.

Vos remarques seront communiquées aux auteurs, hormis celles de la dernière section, facultatives, qui sont destinées exclusivement au comité de rédaction. Nous vous invitons donc à formuler des critiques nettes, mais bienveillantes et constructives, en insistant sur les modifications qui vous semblent utiles pour accroître la pertinence et la qualité des contributions.

**De plus, il vous sera possible de joindre des fichiers que vous veillerez à anonymiser.

Pour toute question, n'hésitez pas à contacter le comité de rédaction de la revue à l'adresse revue-humanites-numeriques@humanisti.ca."**

**Comment by florencedaniel29** [comment]
Fait
