### ISSUE TITLE
Message Nouvelle série d'évaluations à modifier

### ISSUE THREAD

**Issue by florencedaniel29** [emchateau/ojs#63]
Le message du cycle 2 qui crée une nouvelle série d'évaluations n'est pas clair :

"Par défaut, les évaluateurs de la série d'évaluations précédente ont été sélectionnés pour participer à cette nouvelle série". Mais ce n'est pas vrai : à l'étape d'après dans OJS, il faut désigner les évaluateurs.

Peut-on modifier ce message ?

**Comment by emchateau** [comment]
"Vous êtes sur le point de créer une nouvelle série d’évaluations pour cette proposition. Les fichiers qui n’ont pas été utilisés dans les autres séries d’évaluations sont indiqués ci-dessous. Par défaut, les évaluateurs de la série d’évaluations précédente ont été sélectionnés pour participer à cette nouvelle série."
--> supprimer la deuxième phrase

**Comment by emchateau** [comment]
Fait, à poster
